import Head from "next/head";
import { Inter } from "@next/font/google";
import data from "@/data.json";
import Hero from "@/components/Hero";
import About from "@/components/About";
import How from "@/components/How";
import Faq from "@/components/Faq";
import Testimonials from "@/components/Testimonials";
import Footer from "@/components/Footer";
import Copyright from "@/components/Copyright";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="overflow-hidden max-w-[1600px] mx-auto bg-page">
        <Hero
          heroData={data.heroData}
          headerData={data.headerData}
          navData={data.navData}
        />
        <About aboutData={data.aboutData} />
        <How howData={data.howData} />
        <Faq faqData={data.faqData} />
        <Testimonials testimonialData={data.testimonialData} />
        <Footer footerData={data.footerData} />
        <Copyright />
      </div>
    </>
  );
}
